config/routes.rb
Rails.application.routes.draw do
  resources :crmings
  resources :crms
  resources :addressings
  resources :addresses
  resources :orgings
  resources :orgs
  resources :urlings
  resources :urls
  resources :phonings
  resources :phones
  resources :contacts
  resources :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :phonings, as: :phonable
  has_many :phones, through: :phonings

  has_many :urlings, as: :urlable
  has_many :urls, through: :urlings

  has_many :orgings, as: :orgable
  has_many :orgs, through: :orgings

  has_many :addressings, as: :addressable
  has_many :addresses, through: :addressings

  has_many :crmings, as: :crmable
  has_many :crms, through: :crmings
end

app/models/address.rb
class Address < ApplicationRecord
  validates :address, uniqueness: true
  has_many :addressings
  has_many :accounts, through: :addressings, source: :addressable, source_type: :Account
  has_many :contacts, through: :addressings, source: :addressable, source_type: :Contact
end

app/models/addressing.rb
class Addressing < ApplicationRecord
  belongs_to :addressable, polymorphic: true
  belongs_to :address
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :phonings, as: :phonable
  has_many :phones, through: :phonings

  has_many :urlings, as: :urlable
  has_many :urls, through: :urlings

  has_many :orgings, as: :orgable
  has_many :orgs, through: :orgings

  has_many :addressings, as: :addressable
  has_many :addresses, through: :addressings

  has_many :crmings, as: :crmable
  has_many :crms, through: :crmings
end

app/models/crm.rb
class Crm < ApplicationRecord
  validates :crm, uniqueness: true
  has_many :crmings
  has_many :accounts, through: :crmings, source: :crmable, source_type: :Account
  has_many :contacts, through: :crmings, source: :crmable, source_type: :Contact
end

app/models/crming.rb
class Crming < ApplicationRecord
  belongs_to :crmable, polymorphic: true
  belongs_to :crm
end

app/models/org.rb
class Org < ApplicationRecord
  validates :org, uniqueness: true
  has_many :orgings
  has_many :accounts, through: :orgings, source: :orgable, source_type: :Account
  has_many :contacts, through: :orgings, source: :orgable, source_type: :Contact
end

app/models/orging.rb
class Orging < ApplicationRecord
  belongs_to :orgable, polymorphic: true
  belongs_to :org
end

app/models/phone.rb
class Phone < ApplicationRecord
  validates :phone, uniqueness: true
  has_many :phonings
  has_many :accounts, through: :phonings, source: :phonable, source_type: :Account
  has_many :contacts, through: :phonings, source: :phonable, source_type: :Contact
end

app/models/phoning.rb
class Phoning < ApplicationRecord
  belongs_to :phonable, polymorphic: true
  belongs_to :phone
end

app/models/url.rb
class Url < ApplicationRecord
  validates :url, uniqueness: true
  has_many :urlings
  has_many :accounts, through: :urlings, source: :urlable, source_type: :Account
  has_many :contacts, through: :urlings, source: :urlable, source_type: :Contact
end

app/models/urling.rb
class Urling < ApplicationRecord
  belongs_to :urlable, polymorphic: true
  belongs_to :url
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :edit, :update, :destroy]

  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.all
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: 'Url was successfully created.' }
        format.json { render :show, status: :created, location: @url }
      else
        format.html { render :new }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { render :show, status: :ok, location: @url }
      else
        format.html { render :edit }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url, notice: 'Url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:url, :valid)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/crmings_helper.rb
module CrmingsHelper
end

app/helpers/crms_helper.rb
module CrmsHelper
end

app/helpers/orgings_helper.rb
module OrgingsHelper
end

app/helpers/orgs_helper.rb
module OrgsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/phonings_helper.rb
module PhoningsHelper
end

app/helpers/urlings_helper.rb
module UrlingsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/urls/_form.html.erb
<%= form_with(model: url, local: true) do |form| %>
  <% if url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :url_url %>
  </div>

  <div class="field">
    <%= form.label :valid %>
    <%= form.check_box :valid, id: :url_valid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/urls/edit.html.erb
<h1>Editing Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

app/views/urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Urls</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Valid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.url %></td>
        <td><%= url.valid %></td>
        <td><%= link_to 'Show', url %></td>
        <td><%= link_to 'Edit', edit_url_path(url) %></td>
        <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Url', new_url_path %>

app/views/urls/new.html.erb
<h1>New Url</h1>

<%= render 'form', url: @url %>

<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @url.url %>
</p>

<p>
  <strong>Valid:</strong>
  <%= @url.valid %>
</p>

<%= link_to 'Edit', edit_url_path(@url) %> |
<%= link_to 'Back', urls_path %>