config/routes.rb
Rails.application.routes.draw do
  resources :crmings
  resources :crms
  resources :addressings
  resources :addresses
  resources :orgings
  resources :orgs
  resources :urlings
  resources :urls
  resources :phonings
  resources :phones
  resources :contacts
  resources :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :phonings, as: :phonable
  has_many :phones, through: :phonings

  has_many :urlings, as: :urlable
  has_many :urls, through: :urlings

  has_many :orgings, as: :orgable
  has_many :orgs, through: :orgings

  has_many :addressings, as: :addressable
  has_many :addresses, through: :addressings

  has_many :crmings, as: :crmable
  has_many :crms, through: :crmings
end

app/models/address.rb
class Address < ApplicationRecord
  validates :address, uniqueness: true
  has_many :addressings
  has_many :accounts, through: :addressings, source: :addressable, source_type: :Account
  has_many :contacts, through: :addressings, source: :addressable, source_type: :Contact
end

app/models/addressing.rb
class Addressing < ApplicationRecord
  belongs_to :addressable, polymorphic: true
  belongs_to :address
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :phonings, as: :phonable
  has_many :phones, through: :phonings

  has_many :urlings, as: :urlable
  has_many :urls, through: :urlings

  has_many :orgings, as: :orgable
  has_many :orgs, through: :orgings

  has_many :addressings, as: :addressable
  has_many :addresses, through: :addressings

  has_many :crmings, as: :crmable
  has_many :crms, through: :crmings
end

app/models/crm.rb
class Crm < ApplicationRecord
  validates :crm, uniqueness: true
  has_many :crmings
  has_many :accounts, through: :crmings, source: :crmable, source_type: :Account
  has_many :contacts, through: :crmings, source: :crmable, source_type: :Contact
end

app/models/crming.rb
class Crming < ApplicationRecord
  belongs_to :crmable, polymorphic: true
  belongs_to :crm
end

app/models/org.rb
class Org < ApplicationRecord
  validates :org, uniqueness: true
  has_many :orgings
  has_many :accounts, through: :orgings, source: :orgable, source_type: :Account
  has_many :contacts, through: :orgings, source: :orgable, source_type: :Contact
end

app/models/orging.rb
class Orging < ApplicationRecord
  belongs_to :orgable, polymorphic: true
  belongs_to :org
end

app/models/phone.rb
class Phone < ApplicationRecord
  validates :phone, uniqueness: true
  has_many :phonings
  has_many :accounts, through: :phonings, source: :phonable, source_type: :Account
  has_many :contacts, through: :phonings, source: :phonable, source_type: :Contact
end

app/models/phoning.rb
class Phoning < ApplicationRecord
  belongs_to :phonable, polymorphic: true
  belongs_to :phone
end

app/models/url.rb
class Url < ApplicationRecord
  validates :url, uniqueness: true
  has_many :urlings
  has_many :accounts, through: :urlings, source: :urlable, source_type: :Account
  has_many :contacts, through: :urlings, source: :urlable, source_type: :Contact
end

app/models/urling.rb
class Urling < ApplicationRecord
  belongs_to :urlable, polymorphic: true
  belongs_to :url
end

app/controllers/crms_controller.rb
class CrmsController < ApplicationController
  before_action :set_crm, only: [:show, :edit, :update, :destroy]

  # GET /crms
  # GET /crms.json
  def index
    @crms = Crm.all
  end

  # GET /crms/1
  # GET /crms/1.json
  def show
  end

  # GET /crms/new
  def new
    @crm = Crm.new
  end

  # GET /crms/1/edit
  def edit
  end

  # POST /crms
  # POST /crms.json
  def create
    @crm = Crm.new(crm_params)

    respond_to do |format|
      if @crm.save
        format.html { redirect_to @crm, notice: 'Crm was successfully created.' }
        format.json { render :show, status: :created, location: @crm }
      else
        format.html { render :new }
        format.json { render json: @crm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crms/1
  # PATCH/PUT /crms/1.json
  def update
    respond_to do |format|
      if @crm.update(crm_params)
        format.html { redirect_to @crm, notice: 'Crm was successfully updated.' }
        format.json { render :show, status: :ok, location: @crm }
      else
        format.html { render :edit }
        format.json { render json: @crm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crms/1
  # DELETE /crms/1.json
  def destroy
    @crm.destroy
    respond_to do |format|
      format.html { redirect_to crms_url, notice: 'Crm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crm
      @crm = Crm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crm_params
      params.require(:crm).permit(:crm_id, :type, :source)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/crmings_helper.rb
module CrmingsHelper
end

app/helpers/crms_helper.rb
module CrmsHelper
end

app/helpers/orgings_helper.rb
module OrgingsHelper
end

app/helpers/orgs_helper.rb
module OrgsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/phonings_helper.rb
module PhoningsHelper
end

app/helpers/urlings_helper.rb
module UrlingsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/crms/_form.html.erb
<%= form_with(model: crm, local: true) do |form| %>
  <% if crm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crm.errors.count, "error") %> prohibited this crm from being saved:</h2>

      <ul>
      <% crm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :crm_id %>
    <%= form.text_field :crm_id, id: :crm_crm_id %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :type, id: :crm_type %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source, id: :crm_source %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crms/edit.html.erb
<h1>Editing Crm</h1>

<%= render 'form', crm: @crm %>

<%= link_to 'Show', @crm %> |
<%= link_to 'Back', crms_path %>

app/views/crms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crms</h1>

<table>
  <thead>
    <tr>
      <th>Crm</th>
      <th>Type</th>
      <th>Source</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crms.each do |crm| %>
      <tr>
        <td><%= crm.crm_id %></td>
        <td><%= crm.type %></td>
        <td><%= crm.source %></td>
        <td><%= link_to 'Show', crm %></td>
        <td><%= link_to 'Edit', edit_crm_path(crm) %></td>
        <td><%= link_to 'Destroy', crm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crm', new_crm_path %>

app/views/crms/new.html.erb
<h1>New Crm</h1>

<%= render 'form', crm: @crm %>

<%= link_to 'Back', crms_path %>

app/views/crms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Crm:</strong>
  <%= @crm.crm_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @crm.type %>
</p>

<p>
  <strong>Source:</strong>
  <%= @crm.source %>
</p>

<%= link_to 'Edit', edit_crm_path(@crm) %> |
<%= link_to 'Back', crms_path %>